package com.example.agristation1.fakedata

import com.example.agristation1.data.fieldDetails.FieldConnectivity
import com.example.agristation1.data.fieldDetails.FieldDetails
import com.example.agristation1.data.fieldDetails.FieldHealth
import com.example.agristation1.data.fieldDetails.FieldLifecycle

object FakeFieldData {

    val fields = listOf(
        FieldDetails(
            id = 101,
            farmId = 1,
            title = "North Field",
            area = 12.5,
            type = "WHEAT",
            soilMoisture = 41.0,
            lastValidSoilMoisture = 41.0,
            soilTemperature = 18.0,
            lastValidSoilTemperature = 18.0,
            airTemperature = 24.0,
            lastValidAirTemperature = 24.0,
            airHumidity = 58.0,
            lastValidAirHumidity = 58.0,
            lux = 32000.0,
            lastValidLux = 32000.0,
            totalSensors = 3,
            activeSensors = 3,
            health = FieldHealth.HEALTHY,
            connectivity = FieldConnectivity.ONLINE,
            lifecycle = FieldLifecycle.ACTIVE
        ),
        FieldDetails(
            id = 102,
            farmId = 1,
            title = "South Field",
            area = 9.8,
            type = "CORN",
            soilMoisture = 27.0,
            lastValidSoilMoisture = 29.0,
            soilTemperature = 20.0,
            lastValidSoilTemperature = 20.0,
            airTemperature = 29.0,
            lastValidAirTemperature = 29.0,
            airHumidity = 46.0,
            lastValidAirHumidity = 46.0,
            lux = 41000.0,
            lastValidLux = 41000.0,
            totalSensors = 2,
            activeSensors = 1,
            health = FieldHealth.WARNING,
            connectivity = FieldConnectivity.PARTIAL,
            lifecycle = FieldLifecycle.ACTIVE
        ),
        FieldDetails(
            id = 103,
            farmId = 1,
            title = "East Orchard",
            area = 6.2,
            type = "APPLE",
            soilMoisture = 35.0,
            lastValidSoilMoisture = 35.0,
            soilTemperature = 16.0,
            lastValidSoilTemperature = 16.0,
            airTemperature = 22.0,
            lastValidAirTemperature = 22.0,
            airHumidity = 63.0,
            lastValidAirHumidity = 63.0,
            lux = 28000.0,
            lastValidLux = 28000.0,
            totalSensors = 3,
            activeSensors = 2,
            health = FieldHealth.WARNING,
            connectivity = FieldConnectivity.PARTIAL,
            lifecycle = FieldLifecycle.ACTIVE
        ),
        FieldDetails(
            id = 104,
            farmId = 1,
            title = "West Greenhouse",
            area = 3.4,
            type = "TOMATO",
            soilMoisture = 52.0,
            lastValidSoilMoisture = 52.0,
            soilTemperature = 23.0,
            lastValidSoilTemperature = 23.0,
            airTemperature = 27.0,
            lastValidAirTemperature = 27.0,
            airHumidity = 71.0,
            lastValidAirHumidity = 71.0,
            lux = 18000.0,
            lastValidLux = 18000.0,
            totalSensors = 2,
            activeSensors = 2,
            health = FieldHealth.HEALTHY,
            connectivity = FieldConnectivity.ONLINE,
            lifecycle = FieldLifecycle.ACTIVE
        ),
        FieldDetails(
            id = 105,
            farmId = 1,
            title = "Archived Field",
            area = 3.4,
            type = "ORANGE",
            soilMoisture = 52.0,
            lastValidSoilMoisture = 52.0,
            soilTemperature = 23.0,
            lastValidSoilTemperature = 23.0,
            airTemperature = 27.0,
            lastValidAirTemperature = 27.0,
            airHumidity = 71.0,
            lastValidAirHumidity = 71.0,
            lux = 18000.0,
            lastValidLux = 18000.0,
            totalSensors = 2,
            activeSensors = 2,
            health = FieldHealth.HEALTHY,
            connectivity = FieldConnectivity.OFFLINE,
            lifecycle = FieldLifecycle.ARCHIVED
        )
    )
}